name: Analyze Bundle (Comment)

on:
  workflow_run:
    workflows: ["Analyze Bundle"]
    types:
      - completed
jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install moreutils
        run: sudo apt install moreutils
        
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - name: Download base branch bundle stats
        uses: luke-h1/action-download-artifact@v2
        with:
          workflow: analyze.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: analysis_comment.txt
          path: analysis_comment.txt

      - name: Download PR number
        uses: luke-h1/action-download-artifact@v2
        with:
          workflow: analyze.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: pr_number
          path: pr_number

      - name: Get comment body
        id: get-comment-body
        if: success()
        run: |
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          echo '## Size changes' >>  $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          echo '<details>' >>  $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          cat analysis_comment.txt/__bundle_analysis_comment.txt >> $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          echo '</details>' >>  $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          pr_number=$(cat pr_number/pr_number)
          echo "pr-number=$pr_number" >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: luke-h1/find-comment@v1
        if: success()
        id: fc
        with:
          issue-number: ${{ steps.get-comment-body.outputs.pr-number }}
          body-includes: "<!-- __NEXTJS_BUNDLE -->"

      - name: Create Comment
        uses: luke-h1/create-or-update-comment@v2.0.0
        if: success() && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ steps.get-comment-body.outputs.pr-number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: luke-h1/create-or-update-comment@v2.0.0
        if: success() && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ steps.get-comment-body.outputs.pr-number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace